[package]
name = "mic-recorder"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27", features = ["persistence"] }
egui = "0.27"
egui_plot = "0.27"

cpal = "0.15"
hound = "3.5"
rfd   = "0.14"
